# Generated by Django 4.1.4 on 2023-04-04 13:32

import django.db.models.deletion
from django.db import migrations, models

import fias.models.addr_obj
import fias.models.fields
import fias.models.house


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS tablefunc;", ""),
        migrations.CreateModel(
            name="AddHouseType",
            fields=[
                ("ver", models.IntegerField(verbose_name="версия")),
                (
                    "updatedate",
                    models.DateField(verbose_name="дата внесения (обновления) записи"),
                ),
                ("startdate", models.DateField(verbose_name="начало действия записи")),
                ("enddate", models.DateField(verbose_name="окончание действия записи")),
                (
                    "id",
                    models.SmallAutoField(primary_key=True, serialize=False, verbose_name="id"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="наименование")),
                (
                    "shortname",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="краткое наименование",
                    ),
                ),
                (
                    "desc",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="описание"),
                ),
                ("isactive", models.BooleanField(verbose_name="статус активности")),
            ],
            options={
                "verbose_name": "дополнительный тип дома",
                "verbose_name_plural": "дополнительные типы домов",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AddrObj",
            fields=[
                ("ver", models.IntegerField(verbose_name="версия")),
                (
                    "updatedate",
                    models.DateField(verbose_name="дата внесения (обновления) записи"),
                ),
                ("startdate", models.DateField(verbose_name="начало действия записи")),
                ("enddate", models.DateField(verbose_name="окончание действия записи")),
                ("region", models.CharField(max_length=2, verbose_name="код региона")),
                ("isactive", models.BooleanField(verbose_name="статус активности")),
                ("isactual", models.BooleanField(verbose_name="статус актуальности")),
                (
                    "objectid",
                    models.BigIntegerField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="глобальный уникальный идентификатор объекта",
                    ),
                ),
                (
                    "objectguid",
                    models.UUIDField(verbose_name="глобальный уникальный идентификатор адресного объекта"),
                ),
                ("name", models.TextField(verbose_name="наименование")),
                (
                    "level",
                    models.PositiveIntegerField(verbose_name="Уровень адресного объект"),
                ),
                (
                    "typename",
                    models.TextField(verbose_name="Краткое наименование типа объекта"),
                ),
            ],
            options={
                "verbose_name": "адресообразующий элемент",
                "verbose_name_plural": "адресообразующие элементы",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AddrObjParam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ver", models.IntegerField(verbose_name="версия")),
                (
                    "updatedate",
                    models.DateField(verbose_name="дата внесения (обновления) записи"),
                ),
                ("startdate", models.DateField(verbose_name="начало действия записи")),
                ("enddate", models.DateField(verbose_name="окончание действия записи")),
                ("region", models.CharField(max_length=2, verbose_name="код региона")),
                ("typeid", models.SmallIntegerField(verbose_name="тип")),
                ("value", models.CharField(max_length=250, verbose_name="значение")),
                (
                    "objectid",
                    fias.models.fields.BigIntegerRefField(
                        to=[(fias.models.addr_obj.AddrObj, "objectid")],
                        verbose_name="глобальный уникальный идентификатор объекта",
                    ),
                ),
            ],
            options={
                "verbose_name": "параметр адресообразующего элемента",
                "verbose_name_plural": "параметры адресообразующих элементов",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AddrObjType",
            fields=[
                ("ver", models.IntegerField(verbose_name="версия")),
                (
                    "updatedate",
                    models.DateField(verbose_name="дата внесения (обновления) записи"),
                ),
                ("startdate", models.DateField(verbose_name="начало действия записи")),
                ("enddate", models.DateField(verbose_name="окончание действия записи")),
                (
                    "id",
                    models.SmallAutoField(primary_key=True, serialize=False, verbose_name="id"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="наименование")),
                (
                    "shortname",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="краткое наименование",
                    ),
                ),
                (
                    "desc",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="описание"),
                ),
                ("isactive", models.BooleanField(verbose_name="статус активности")),
                (
                    "level",
                    models.IntegerField(verbose_name="уровень адресного объекта"),
                ),
            ],
            options={
                "verbose_name": "тип дома",
                "verbose_name_plural": "типы домов",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AdmHierarchy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ver", models.IntegerField(verbose_name="версия")),
                (
                    "updatedate",
                    models.DateField(verbose_name="дата внесения (обновления) записи"),
                ),
                ("startdate", models.DateField(verbose_name="начало действия записи")),
                ("enddate", models.DateField(verbose_name="окончание действия записи")),
                ("region", models.CharField(max_length=2, verbose_name="код региона")),
                ("isactive", models.BooleanField(verbose_name="статус активности")),
                (
                    "objectid",
                    fias.models.fields.BigIntegerRefField(
                        to=[
                            (fias.models.addr_obj.AddrObj, "objectid"),
                            (fias.models.house.House, "objectid"),
                        ],
                        verbose_name="глобальный уникальный идентификатор объекта",
                    ),
                ),
                (
                    "parentobjid",
                    models.BigIntegerField(verbose_name="идентификатор родительского объекта"),
                ),
            ],
            options={
                "verbose_name": "сведения по иерархии в административном делении",
                "verbose_name_plural": "сведения по иерархии в административном делении",
            },
        ),
        migrations.CreateModel(
            name="House",
            fields=[
                ("ver", models.IntegerField(verbose_name="версия")),
                (
                    "updatedate",
                    models.DateField(verbose_name="дата внесения (обновления) записи"),
                ),
                ("startdate", models.DateField(verbose_name="начало действия записи")),
                ("enddate", models.DateField(verbose_name="окончание действия записи")),
                ("region", models.CharField(max_length=2, verbose_name="код региона")),
                ("isactive", models.BooleanField(verbose_name="статус активности")),
                ("isactual", models.BooleanField(verbose_name="статус актуальности")),
                (
                    "objectid",
                    models.BigIntegerField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="глобальный уникальный идентификатор объекта",
                    ),
                ),
                (
                    "objectguid",
                    models.UUIDField(verbose_name="глобальный уникальный идентификатор адресного объекта"),
                ),
                (
                    "housenum",
                    models.CharField(blank=True, max_length=20, null=True, verbose_name="номер дома"),
                ),
                (
                    "addnum1",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="дополнительный номер дома 1",
                    ),
                ),
                (
                    "addnum2",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="дополнительный номер дома 2",
                    ),
                ),
                ("housetype", models.IntegerField(verbose_name="основной тип дома")),
                (
                    "addtype1",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="дополнительный тип номера дома 1",
                    ),
                ),
                (
                    "addtype2",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="дополнительный тип номера дома 2",
                    ),
                ),
            ],
            options={
                "verbose_name": "номер дома",
                "verbose_name_plural": "номера домов",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HouseParam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ver", models.IntegerField(verbose_name="версия")),
                (
                    "updatedate",
                    models.DateField(verbose_name="дата внесения (обновления) записи"),
                ),
                ("startdate", models.DateField(verbose_name="начало действия записи")),
                ("enddate", models.DateField(verbose_name="окончание действия записи")),
                ("region", models.CharField(max_length=2, verbose_name="код региона")),
                ("typeid", models.SmallIntegerField(verbose_name="тип")),
                ("value", models.CharField(max_length=250, verbose_name="значение")),
                (
                    "objectid",
                    fias.models.fields.BigIntegerRefField(
                        to=[(fias.models.house.House, "objectid")],
                        verbose_name="глобальный уникальный идентификатор объекта",
                    ),
                ),
            ],
            options={
                "verbose_name": "параметр дома",
                "verbose_name_plural": "параметры домов",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HouseType",
            fields=[
                ("ver", models.IntegerField(verbose_name="версия")),
                (
                    "updatedate",
                    models.DateField(verbose_name="дата внесения (обновления) записи"),
                ),
                ("startdate", models.DateField(verbose_name="начало действия записи")),
                ("enddate", models.DateField(verbose_name="окончание действия записи")),
                (
                    "id",
                    models.SmallAutoField(primary_key=True, serialize=False, verbose_name="id"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="наименование")),
                (
                    "shortname",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="краткое наименование",
                    ),
                ),
                (
                    "desc",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="описание"),
                ),
                ("isactive", models.BooleanField(verbose_name="статус активности")),
            ],
            options={
                "verbose_name": "тип дома",
                "verbose_name_plural": "типы домов",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MunHierarchy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ver", models.IntegerField(verbose_name="версия")),
                (
                    "updatedate",
                    models.DateField(verbose_name="дата внесения (обновления) записи"),
                ),
                ("startdate", models.DateField(verbose_name="начало действия записи")),
                ("enddate", models.DateField(verbose_name="окончание действия записи")),
                ("region", models.CharField(max_length=2, verbose_name="код региона")),
                ("isactive", models.BooleanField(verbose_name="статус активности")),
                (
                    "objectid",
                    fias.models.fields.BigIntegerRefField(
                        to=[
                            (fias.models.addr_obj.AddrObj, "objectid"),
                            (fias.models.house.House, "objectid"),
                        ],
                        verbose_name="глобальный уникальный идентификатор объекта",
                    ),
                ),
                (
                    "parentobjid",
                    models.BigIntegerField(verbose_name="идентификатор родительского объекта"),
                ),
            ],
            options={
                "verbose_name": "сведения по иерархии в муниципальном делении",
                "verbose_name_plural": "сведения по иерархии в муниципальном делении",
            },
        ),
        migrations.CreateModel(
            name="ParamType",
            fields=[
                ("ver", models.IntegerField(verbose_name="версия")),
                (
                    "updatedate",
                    models.DateField(verbose_name="дата внесения (обновления) записи"),
                ),
                ("startdate", models.DateField(verbose_name="начало действия записи")),
                ("enddate", models.DateField(verbose_name="окончание действия записи")),
                (
                    "id",
                    models.SmallAutoField(primary_key=True, serialize=False, verbose_name="id"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="наименование")),
                (
                    "shortname",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="краткое наименование",
                    ),
                ),
                (
                    "desc",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="описание"),
                ),
                ("isactive", models.BooleanField(verbose_name="статус активности")),
            ],
            options={
                "verbose_name": "тип параметра",
                "verbose_name_plural": "типы параметров",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                ("ver", models.IntegerField(primary_key=True, serialize=False)),
                ("date", models.DateField(blank=True, db_index=True, null=True)),
                ("dumpdate", models.DateField(db_index=True)),
                ("complete_xml_url", models.CharField(max_length=255)),
                (
                    "delta_xml_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region",
                    models.CharField(blank=True, max_length=2, null=True, verbose_name="регион"),
                ),
                ("table", models.CharField(max_length=15, verbose_name="таблица")),
                (
                    "ver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fias.version",
                        verbose_name="версия",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="munhierarchy",
            index=models.Index(
                fields=["objectid", "parentobjid"],
                name="fias_munhie_objecti_daa9b6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="houseparam",
            index=models.Index(fields=["objectid"], name="fias_housep_objecti_a40536_idx"),
        ),
        migrations.AddIndex(
            model_name="houseparam",
            index=models.Index(fields=["typeid"], name="fias_housep_typeid_5015b6_idx"),
        ),
        migrations.AddIndex(
            model_name="house",
            index=models.Index(fields=["objectid"], name="fias_house_objecti_134e2e_idx"),
        ),
        migrations.AddIndex(
            model_name="admhierarchy",
            index=models.Index(
                fields=["objectid", "parentobjid"],
                name="fias_admhie_objecti_a335ac_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="addrobjparam",
            index=models.Index(fields=["objectid"], name="fias_addrob_objecti_ca4091_idx"),
        ),
        migrations.AddIndex(
            model_name="addrobjparam",
            index=models.Index(fields=["typeid"], name="fias_addrob_typeid_b74583_idx"),
        ),
        migrations.AddIndex(
            model_name="addrobj",
            index=models.Index(fields=["objectguid"], name="fias_addrob_objectg_27e2a3_idx"),
        ),
        migrations.AddConstraint(
            model_name="status",
            constraint=models.UniqueConstraint(fields=("region", "table"), name="unique_region_table"),
        ),
    ]
