# Generated by Django 4.2 on 2023-08-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fias", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admhierarchy",
            name="parentobjid",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="идентификатор родительского объекта"),
        ),
        migrations.AlterField(
            model_name="house",
            name="housetype",
            field=models.IntegerField(blank=True, null=True, verbose_name="основной тип дома"),
        ),
        migrations.AlterField(
            model_name="munhierarchy",
            name="parentobjid",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="идентификатор родительского объекта"),
        ),
    ]
